// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.bt.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TorrentApiPigeonUtils {

  fun createConnectionError(channelName: String): TorrentApiException {
    return TorrentApiException("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is TorrentApiException) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class TorrentApiException (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 下载进度数据
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DownloadProgressData (
  val infoHash: String,
  val name: String,
  val totalBytes: Long,
  val downloadedBytes: Long,
  val uploadBytes: Long,
  val progressPercent: Double,
  val downloadSpeed: Long,
  val uploadSpeed: Long,
  val etaSeconds: Long,
  val status: Long,
  val connectedPeers: Long,
  val connectedSeeds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadProgressData {
      val infoHash = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val totalBytes = pigeonVar_list[2] as Long
      val downloadedBytes = pigeonVar_list[3] as Long
      val uploadBytes = pigeonVar_list[4] as Long
      val progressPercent = pigeonVar_list[5] as Double
      val downloadSpeed = pigeonVar_list[6] as Long
      val uploadSpeed = pigeonVar_list[7] as Long
      val etaSeconds = pigeonVar_list[8] as Long
      val status = pigeonVar_list[9] as Long
      val connectedPeers = pigeonVar_list[10] as Long
      val connectedSeeds = pigeonVar_list[11] as Long
      return DownloadProgressData(infoHash, name, totalBytes, downloadedBytes, uploadBytes, progressPercent, downloadSpeed, uploadSpeed, etaSeconds, status, connectedPeers, connectedSeeds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      infoHash,
      name,
      totalBytes,
      downloadedBytes,
      uploadBytes,
      progressPercent,
      downloadSpeed,
      uploadSpeed,
      etaSeconds,
      status,
      connectedPeers,
      connectedSeeds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DownloadProgressData) {
      return false
    }
    if (this === other) {
      return true
    }
    return TorrentApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * 种子文件信息
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TorrentFileData (
  val index: Long,
  val path: String,
  val name: String,
  val sizeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TorrentFileData {
      val index = pigeonVar_list[0] as Long
      val path = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      val sizeBytes = pigeonVar_list[3] as Long
      return TorrentFileData(index, path, name, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      path,
      name,
      sizeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TorrentFileData) {
      return false
    }
    if (this === other) {
      return true
    }
    return TorrentApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class TorrentApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadProgressData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TorrentFileData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DownloadProgressData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TorrentFileData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API — Dart 调用 Kotlin
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TorrentHostApi {
  /** 启动下载 */
  fun startDownload(magnetUri: String, savePath: String, callback: (Result<String>) -> Unit)
  /** 暂停下载 */
  fun pauseDownload(infoHash: String, callback: (Result<Unit>) -> Unit)
  /** 恢复下载 */
  fun resumeDownload(infoHash: String, callback: (Result<Unit>) -> Unit)
  /** 移除下载 */
  fun removeDownload(infoHash: String, deleteFiles: Boolean, callback: (Result<Unit>) -> Unit)
  /** 获取进度 */
  fun getProgress(infoHash: String, callback: (Result<DownloadProgressData>) -> Unit)
  /** 获取文件列表 */
  fun getFiles(infoHash: String, callback: (Result<List<TorrentFileData>>) -> Unit)
  /** 设置 piece 优先级 */
  fun setPiecePriority(infoHash: String, pieceIndex: Long, priority: Long, callback: (Result<Unit>) -> Unit)
  /** 设置 piece deadline */
  fun setPieceDeadline(infoHash: String, pieceIndex: Long, millis: Long, callback: (Result<Unit>) -> Unit)
  /** 读取已下载 piece 数据 */
  fun readPiece(infoHash: String, pieceIndex: Long, callback: (Result<ByteArray>) -> Unit)

  companion object {
    /** The codec used by TorrentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TorrentApiPigeonCodec()
    }
    /** Sets up an instance of `TorrentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TorrentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val magnetUriArg = args[0] as String
            val savePathArg = args[1] as String
            api.startDownload(magnetUriArg, savePathArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TorrentApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.pauseDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            api.pauseDownload(infoHashArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TorrentApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.resumeDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            api.resumeDownload(infoHashArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TorrentApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.removeDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            val deleteFilesArg = args[1] as Boolean
            api.removeDownload(infoHashArg, deleteFilesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TorrentApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.getProgress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            api.getProgress(infoHashArg) { result: Result<DownloadProgressData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TorrentApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.getFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            api.getFiles(infoHashArg) { result: Result<List<TorrentFileData>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TorrentApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.setPiecePriority$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            val pieceIndexArg = args[1] as Long
            val priorityArg = args[2] as Long
            api.setPiecePriority(infoHashArg, pieceIndexArg, priorityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TorrentApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.setPieceDeadline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            val pieceIndexArg = args[1] as Long
            val millisArg = args[2] as Long
            api.setPieceDeadline(infoHashArg, pieceIndexArg, millisArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(TorrentApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bt_torrent.TorrentHostApi.readPiece$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infoHashArg = args[0] as String
            val pieceIndexArg = args[1] as Long
            api.readPiece(infoHashArg, pieceIndexArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TorrentApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TorrentApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API — Kotlin 调用 Dart（事件回调）
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TorrentFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TorrentFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TorrentApiPigeonCodec()
    }
  }
  /** 进度更新回调 */
  fun onProgressChanged(progressArg: DownloadProgressData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bt_torrent.TorrentFlutterApi.onProgressChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(TorrentApiException(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TorrentApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** 下载完成回调 */
  fun onDownloadFinished(infoHashArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bt_torrent.TorrentFlutterApi.onDownloadFinished$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infoHashArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(TorrentApiException(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TorrentApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** 下载错误回调 */
  fun onDownloadError(infoHashArg: String, errorArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bt_torrent.TorrentFlutterApi.onDownloadError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infoHashArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(TorrentApiException(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TorrentApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
